apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DEBUG: 'True'
  SECRET_KEY: 'cGFzc3dvcmQ='
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/web/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: web:4.0  
        ports:
        - containerPort: 8000
        command: 
          - /bin/sh
          - -c
          - |
            python3 manage.py makemigrations 
            python3 manage.py migrate --no-input
            python manage.py runserver 0.0.0.0:8000
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/myapp/secrets
          readOnly: true
        - name: media-volume
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DEBUG
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: project-config
      volumes:
      - name: secret-volume
        secret:
          secretName: app-secret
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc