apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DEBUG: 'True'
  SECRET_KEY: 'cGFzc3dvcmQ='
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
  - name: mycontainer
    image: web:4.0
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    command: 
      - /bin/sh
      - -c
      - |
        python3 manage.py collectstatic --no-input
        python3 manage.py makemigrations
        python3 manage.py migrate --no-input
        python manage.py runserver 0.0.0.0:8000
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/myapp/secrets
      readOnly: true
    - name: media-volume
      mountPath: media/
    - name: static-volume
      mountPath: static/
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: SECRET_KEY
    - name: DEBUG
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DEBUG
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: REDIS_PASSWORD
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD
    envFrom:
    - configMapRef:
        name: project-config
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
  - name: media-volume
    hostPath:
      path: /mnt/project/media
  - name: static-volume
    hostPath:
      path: /mnt/project/static